wheeled_biped:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

  # Hip Position Controllers ------------------------------------
  left_hip_position_controller:
    # set desired high level control
    type: "effort_controllers/JointPositionController"
    joint: left_hip_joint
    pid: {p: 10.0, i: 0.0, d: 1.0}
  right_hip_position_controller:
    type: "effort_controllers/JointPositionController"
    joint: right_hip_joint
    pid: {p: 10.0, i: 0.0, d: 1.0}

  # Knee Position Controllers ------------------------------------
  left_knee_position_controller:
    type: "effort_controllers/JointPositionController"
    joint: left_knee_joint
    pid: {p: 10.0, i: 0.0, d: 1.0}
  right_knee_position_controller:
    type: "effort_controllers/JointPositionController"
    joint: right_knee_joint
    pid: {p: 10.0, i: 0.0, d: 1.0}

  # Wheel Velocity Controllers -----------------------------------
  left_wheel_velocity_controller:
    type: "effort_controllers/JointVelocityController"
    joint: left_wheel_joint
    pid: {p: 5.0, i: 0.0, d: 0.1}
  right_wheel_velocity_controller:
    type: "effort_controllers/JointVelocityController"
    joint: right_wheel_joint
    pid: {p: 5.0, i: 0.0, d: 0.1}