<?xml version='1.0'?>
<robot name="wheeled_biped" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- XACRO DEFINITIONS -->

    <material name="blue">
       <color rgba="0 0 0.8 1"/>
    </material>

    <!-- Define main chassis parameters -->
    <xacro:property name="mass" value="1.7" />
    <xacro:property name="width" value="0.1" />
    <xacro:property name="length" value="0.15" />
    <xacro:property name="height" value="0.1" />
    
    <!-- Inertia formulas for box -->
    <xacro:macro name="box_inertia" params="m x y z">
        <mass value="${m}"/>
        <inertia ixx="${(1/12) * m * (y*y + z*z)}" ixy="0.0" ixz="0.0"
                iyy="${(1/12) * m * (x*x + z*z)}" iyz="0.0"
                izz="${(1/12) * m * (x*x + y*y)}"/>
    </xacro:macro>

    <!-- Inertia formulas for cylinder -->
    <xacro:macro name="cylinder_inertia" params="m r l">
        <mass value="${m}"/>
        <inertia
            ixx="${1.0/12 * m * (3*r*r + l*l)}"
            ixy="0.0" ixz="0.0"
            iyy="${1.0/12 * m * (3*r*r + l*l)}"
            iyz="0.0"
            izz="${ 1.0/2  * m * (r*r)}"/>
    </xacro:macro>

    <!-- Hip links definition: right side flip = 1, left side flip =-1 -->
    <xacro:macro name = "hip" params = "side flip">
        <link name="${side}_hip">

            <!-- Inertial parameters -->
            <inertial>
                <origin xyz="0 ${flip * 0.015} -0.0875" rpy="0 0 0"/>
                <xacro:box_inertia m="0.15" x="0.06" y="0.03" z="0.175"/>
            </inertial>


            <!-- Collision geometry -->
            <collision name="${side}_hip_collision">
                <origin xyz="0 ${flip * 0.015} -0.0875" rpy="0 0 0"/>
                <geometry>
                    <box size="0.06 0.03 0.175"/>
                </geometry>
            </collision>

            <!-- Visual geometry -->
            <visual name="${side}_hip_visual">
                <origin xyz="0 ${flip * 0.015} -0.0875" rpy="0 0 0"/>
                <geometry>
                    <box size="0.06 0.03 0.175"/>
                </geometry>
            </visual>
        </link>
    </xacro:macro>

    <!-- Hip joint definition: right side flip = 1, left side flip =-1 -->
    <xacro:macro name = "hip_joint" params = "side flip">
        <joint name="${side}_hip_joint" type="revolute">
            <parent link="chassis"/>
            <child  link="${side}_hip"/>
            <origin xyz="0 ${flip * length/2} 0" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <limit lower="-2.53073" upper="2.53073" effort="3.8" velocity="60.0"/>
        </joint>

    </xacro:macro>

    <!-- Knee links defintion-->
    <xacro:macro name = "knee" params = "side">
        <link name="${side}_knee">

            <!-- Inertial parameters -->
            <inertial>
                <origin xyz="0 0 -0.0875" rpy="0 0 0"/>
                <xacro:box_inertia m="0.05" x="0.031" y="0.015" z="0.175"/>
            </inertial>


            <!-- Collision geometry -->
            <collision name="${side}_knee_collision">
                <origin xyz="0 0 -0.0875" rpy="0 0 0"/>
                <geometry>
                    <box size="0.031 0.015 0.175"/>
                </geometry>
            </collision>

            <!-- Visual geometry -->
            <visual name="${side}_knee_visual">
                <origin xyz="0 0 -0.0875" rpy="0 0 0"/>
                <geometry>
                    <box size="0.031 0.015 0.175"/>
                </geometry>
            </visual>
        </link>
    </xacro:macro>

    <!-- Knee joint definition: right side flip = 1, left side flip =-1 -->
    <xacro:macro name = "knee_joint" params = "side flip">
        <joint name="${side}_knee_joint" type="revolute">
            <parent link="${side}_hip"/>
            <child  link="${side}_knee"/>
            <origin xyz="0 ${flip * 0.015} -0.175" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <limit lower="-2.53073" upper="2.53073" effort="3.8" velocity="60.0"/>
        </joint>
    </xacro:macro>
    
    <!-- Wheel links defintion-->
    <xacro:macro name = "wheel" params = "side flip">
        <link name="${side}_wheel">

            <!-- Inertial parameters -->
            <inertial>
                <origin xyz="0 ${flip * 0.0469/2} 0" rpy="1.5708 0 0"/>
                <xacro:cylinder_inertia m="0.7" r="0.06" l="0.0469"/>
            </inertial>


            <!-- Collision geometry -->
            <collision name="${side}_wheel_collision">
                <origin xyz="0 ${flip * 0.0469/2} 0" rpy="1.5708 0 0"/>
                <geometry>
                    <cylinder radius="0.06" length="0.0469"/>
                </geometry>
            </collision>

            <!-- Visual geometry -->
            <visual name="${side}_wheel_visual">
                <origin xyz="0 ${flip * 0.0469/2} 0" rpy="1.5708 0 0"/>
                <geometry>
                    <cylinder radius="0.06" length="0.0469"/>
                </geometry>
            </visual>
        </link>
    </xacro:macro>

    <!-- Wheel joint definition: right side flip = 1, left side flip =-1 -->
    <xacro:macro name = "wheel_joint" params = "side flip">
        <joint name="${side}_wheel_joint" type="continuous">
            <parent link="${side}_knee"/>
            <child  link="${side}_wheel"/>
            <origin xyz="0 ${flip * 0.015/2} -0.175" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <limit effort="3.8" velocity="60.0"/>
        </joint>
    </xacro:macro>

        
    <!-- LINKS DEFINITIONS -->

    <!-- Dummy base link -->
    <link name="base_link"/>
    <joint name="base_to_chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 0" rpy="0 1.5708 0"/>
    </joint>

    <!-- Chassis link -->
    <link name='chassis'>
        <inertial>
            <xacro:box_inertia m="${mass}" x="${width}" y="${length}" z="${height}" />
        </inertial>
        
        <collision name='collision'>
            <geometry> 
                <box size="${width} ${length} ${height}"/>
            </geometry>
        </collision>

        <visual name='visual'>
            <geometry>
                <box size="${width} ${length} ${height}"/>
            </geometry>
        </visual>
    </link>

    <!-- Hip links & Joints-->
    <xacro:hip side = "left" flip = "-1"/>
    <xacro:hip side = "right" flip = "1"/>

    <xacro:hip_joint side = "left" flip = "-1"/>
    <xacro:hip_joint side = "right" flip = "1"/>

    <!-- Knee links & Joints -->
    <xacro:knee side = "left"/>
    <xacro:knee side = "right"/>

    <xacro:knee_joint side = "left" flip = "-1"/>
    <xacro:knee_joint side = "right" flip = "1"/>

    <xacro:wheel side = "left" flip = "-1"/>
    <xacro:wheel side = "right" flip = "1"/>

    <xacro:wheel_joint side = "left" flip = "-1"/>
    <xacro:wheel_joint side = "right" flip = "1"/>

 
    <!-- IMU link -->
    <link name="imu_link">
        <inertial>
            <mass value="0.01"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <!-- approximate a small cube -->
            <inertia 
            ixx="1e-6" ixy="0.0" ixz="0.0"
            iyy="1e-6" iyz="0.0"
            izz="1e-6"/>
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.02 0.02"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>

    <!--Joint IMU to the chassis -->
    <joint name="imu_joint" type="fixed">
        <parent link="chassis"/>
        <child  link="imu_link"/>
        <!-- adjust offset to position the IMU where you like: -->
        <origin xyz="0 0 0.02" rpy="0 0 0"/>
    </joint>

    <gazebo reference="imu_link">
        <sensor name="imu_sensor" type="imu">
            <always_on>true</always_on>
            <update_rate>100</update_rate>
            <visualize>true</visualize>
            <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
                <topicName>/wheeled_biped/imu/data</topicName>
                <frameName>imu_link</frameName>
                <gaussianNoise>0.001</gaussianNoise> <!-- A little noise is more realistic -->
                <initialOrientationAsReference>false</initialOrientationAsReference>
            </plugin>
            <pose>0 0 0 0 0 0</pose>
        </sensor>
    </gazebo>

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/wheeled_biped</robotNamespace>
        </plugin>
    </gazebo>

    <xacro:macro name="transmission" params="joint">
        <transmission name="${joint}_transmission">
            <type>transmission_interface/SimpleTransmission</type>
            <!-- Desired low level control: torque wanted -->
            <joint name="${joint}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>

            <actuator name="${joint}_motor">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    <xacro:transmission joint="left_hip_joint"/>
    <xacro:transmission joint="right_hip_joint"/>
    <xacro:transmission joint="left_knee_joint"/>
    <xacro:transmission joint="right_knee_joint"/>
    <xacro:transmission joint="left_wheel_joint"/>
    <xacro:transmission joint="right_wheel_joint"/>
    
    


   
</robot>



    
